### ISSUE TITLE
Libhooker injection error

### ISSUE THREAD

**Issue by mynovelhost** [Odyssey-Team/Taurine#2]
How to reproduce:
- Create tweak with com.apple.WebKit.Networking target
- Do NSLog in the constructor.

Expected Behavior:
- Outputting a message to the log

Current behavior:
- When starting some applications (Chrome, A-Look ...), there is no message output to the log, in others (Zebra ...) the message is outputed to the log.

Description:
When the com.apple.WebKit.Networking process is created, pspawn_payload-stg2.dylib and TweakInject.dylib are loaded into it, but the tweak with target com.apple.WebKit.Networking is not loaded into process. Inject to webpages = enabled

**Comment by mynovelhost** [comment]
Today found some time to research the problem. For some reason, libhooker entered permanent safemode. A .safemode-{hash} file was created in the Chrome data folder/tmp. On com.apple.WebKit.Networking start this file was detected => Safemode. Also this file wasn't automatically deleted even after reboot/rootfs restore

**Comment by Diatrus** [comment]
Out of date
