### ISSUE TITLE
ERR_JAILBREAK error

### ISSUE THREAD

**Issue by hohoho123456** [Odyssey-Team/Taurine#29]
I’m trying to install taurine beta on my iPhone 8+ running 14.7.1 via TrollStore and every single time I try to jailbreak taurine beta says ERR_JAILBREAK. please help. Thanks.

![A1E52CBA-3508-4251-A31D-A79AB89D2335](https://github.com/Odyssey-Team/Taurine/assets/44559677/bd541762-1ee8-46ed-9249-b792e211a4bf)

**Comment by AdverseMiller** [comment]
did you restorerootfs on your previous jailbreak

**Comment by hohoho123456** [comment]
> 

Yes. I restoredrootFS from checkra1n. Thanks.

**Comment by AdverseMiller** [comment]
Not good enough, I had the same issue. You have to jailbreak with odysseyra1n and then use taurine.

**Comment by hohoho123456** [comment]
> odysseyra1n

How do I install odysseyra1n?

**Comment by AdverseMiller** [comment]
https://github.com/raspberryenvoie/odysseyn1x

**Comment by hohoho123456** [comment]
![Uploading 9A432FC8-FB15-4AC2-BB3C-F24B2B185CC4.png…]()

Installing odysseyra1n worked. Thanks!
