### ISSUE TITLE
Hello.

### ISSUE THREAD

**Issue by hypernatremia** [Odyssey-Team/Taurine#3]
I have recently jailbroken my ios 14.2 iphone 11 pro max with Taurine. However some issues has arisen. I can't seem to access my settings. Each time I try to access my settings it crashes. In sileo when updating, downloading or trying to delete a tweak, when restart springboard pop up is visible it doesn't comply. It does nothing. The tweak i installed, that i suspect is the culprit, changed the appearance of settings so that tweaks are made accessible at the top of settings. 

Anyone know how to fix the issue i have? Or has any suggestions?

**Comment by Diatrus** [comment]
Out of date
