### ISSUE TITLE
[SUGESTION] make the logo displayed during userspace reboot themeable?

### ISSUE THREAD

**Issue by Witherking25** [Odyssey-Team/Taurine#6]
Instead of embedding the “boot logo” in the jailbreakd binary, can it be put separately so that it can be themed?
Or maybe if it detects an image in a specific spot it uses that one instead?

**Comment by Witherking25** [comment]
I miss my boot logo I had on my old iOS 7.x iPod touch

**Comment by CallMeEchoCodes** [comment]
i need this so i can make tec tip setup

**Comment by paranmat** [comment]
can't, jailbreakd is not open source so u can't do that

**Comment by Witherking25** [comment]
How’d the taurine logo get in there if they don’t have the source?

**Comment by Witherking25** [comment]
This isn’t a pull request it’s a feature request

**Comment by paranmat** [comment]
> How’d the taurine logo get in there if they don’t have the source?

bruhhh, they're hiding the source for jailbreakd, they have it, they're just not releasing it bro
